# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyazure < Formula
  desc "The lazy way to view your Azure resources. TUI for drilling down into Azure subscriptions, resource groups and resources."
  homepage "https://github.com/matsest/lazyazure"
  version "0.4.3-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matsest/lazyazure/releases/download/v0.4.3-alpha/lazyazure_0.4.3-alpha_darwin_amd64"
      sha256 "22cdcb1920d3b0b0a066267860a2b246f829d86a896d470eb398e33d2c2a23ba"

      define_method(:install) do
        bin.install "lazyazure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matsest/lazyazure/releases/download/v0.4.3-alpha/lazyazure_0.4.3-alpha_darwin_arm64"
      sha256 "7a1d9c21837a5d154dc783381cea0ab0f5b9694bf1f1884e4127ff4b4e700ee9"

      define_method(:install) do
        bin.install "lazyazure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsest/lazyazure/releases/download/v0.4.3-alpha/lazyazure_0.4.3-alpha_linux_amd64"
      sha256 "4971919bf92308f88f39e84593e560147c689f958c6be3f54aa59b20130903b8"
      define_method(:install) do
        bin.install "lazyazure"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsest/lazyazure/releases/download/v0.4.3-alpha/lazyazure_0.4.3-alpha_linux_arm64"
      sha256 "2918aa47fc531c16733c4ebd7d9a03f2df736c5df384a246c3702f7ec825ff73"
      define_method(:install) do
        bin.install "lazyazure"
      end
    end
  end

  test do
    system "#{bin}/lazyazure", "--help"
  end
end
