# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyazure < Formula
  desc "The lazy way to view your Azure resources. TUI for drilling down into Azure subscriptions, resource groups and resources."
  homepage "https://github.com/matsest/lazyazure"
  version "0.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matsest/lazyazure/releases/download/v0.4.4/lazyazure_0.4.4_darwin_amd64"
      sha256 "e17905cdb67008228974de38558e15178e7c709ff22a413296bbbbe848abc1b9"

      define_method(:install) do
        bin.install "lazyazure_0.4.4_darwin_amd64" => "lazyazure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matsest/lazyazure/releases/download/v0.4.4/lazyazure_0.4.4_darwin_arm64"
      sha256 "4331cb53fffcb619cc7fc4cc735520f338d7e42ac22b5bad7b73da8334b89ac4"

      define_method(:install) do
        bin.install "lazyazure_0.4.4_darwin_arm64" => "lazyazure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsest/lazyazure/releases/download/v0.4.4/lazyazure_0.4.4_linux_amd64"
      sha256 "763513c18fd3a2d4f660936eaac3b4ecae92fdd70ae593ed79d47e60ab931c84"
      define_method(:install) do
        bin.install "lazyazure_0.4.4_linux_amd64" => "lazyazure"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matsest/lazyazure/releases/download/v0.4.4/lazyazure_0.4.4_linux_arm64"
      sha256 "ba41ad0208e0a7206eaa3ad1c2670735e2af4e67fb63d3f7e3826e0bb35a45c5"
      define_method(:install) do
        bin.install "lazyazure_0.4.4_linux_arm64" => "lazyazure"
      end
    end
  end

  test do
    system "#{bin}/lazyazure", "--help"
  end
end
